### ISSUE TITLE
monitor_15_4.c:34:23: fatal error: pcap/pcap.h: No such file or directory

### ISSUE THREAD

**Issue by PeijieLi** [zephyrproject-rtos/net-tools#23]
I am trying to setup networking with qemu by following the instructions [here](https://docs.zephyrproject.org/1.11.0/subsystems/networking/qemu_setup.html#networking-with-qemu)
Yet the make command (in the prerequisite section) fails and the error message is 

$ make
cc -c -o monitor_15_4.o  `pkg-config --cflags --libs glib-2.0` monitor_15_4.c
monitor_15_4.c:34:23: fatal error: pcap/pcap.h: No such file or directory
compilation terminated.
Makefile:51: recipe for target 'monitor_15_4.o' failed
make: *** [monitor_15_4.o] Error 1

**Comment by tbursztyka** [comment]
Hi,

Looks like you are missing libpcap or it's develepment package in your
installation.

Tomasz

**Comment by PeijieLi** [comment]
Ah that fixed it. Thank you very much!
